apiVersion: container.gcp.crossplane.io/v1beta2
kind: Cluster
metadata:
  name: gcp-k8s
  labels:
    service: gke
    creation: crossplane
spec:
  forProvider:
    location: europe-west9
    autopilot:
      enabled: true
  providerConfigRef:
    name: gcp-provider-config
  writeConnectionSecretToRef:
    name: gcp-k8s
    namespace: default