apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpl
spec:
  minReadySeconds: 15
  replicas: 1
  template:
    spec:
      containers:
      - name: manifest-syncer
        image: dagandersen/manifest-syncer:v0.0.12
        resources:
          requests:
            cpu: "0"
            memory: "0"
          limits:
            cpu: "250m"
            memory: "1Gi"