apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-packages
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/dag-andersen/k8s-ucp-core-gitops
    targetRevision: HEAD
    path: ./crossplane-packages/configurations
  destination:
    server: https://kubernetes.default.svc
    namespace: default