apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: do-provider
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/dag-andersen/k8s-core-infra
    targetRevision: HEAD
    path: ./do-provider
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}