apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gcp-provider
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/dag-andersen/k8s-ucp-core-gitops
    targetRevision: HEAD
    path: ./gcp-provider
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true