apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gcp-cluster-stage
  namespace: argocd
  labels:
    hasEnvs: "yes"
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/dag-andersen/k8s-core-infra
    targetRevision: HEAD
    path: ./gcp-clusters/overlays/stage
  destination:
    server: https://kubernetes.default.svc
    namespace: default