apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- projects.yml
- argo-config.yml
- crossplane.yml
- prometheus.yml
# - do-provider.yml
# - aws-provider.yml
# - aws-database.yml
- gcp-provider.yml
- gcp-database.yml
- gcp-cluster-prod.yml
- gcp-cluster-stage.yml
- manifest-syncer.yml