apiVersion: container.gcp.upbound.io/v1beta1
kind: Cluster
metadata:
  name: gcp-k8s
  labels:
    service: gke
    creation: crossplane
spec:
  forProvider:
    addonsConfig:
      networkPolicyConfig:
        disabled: false
    networkRef:
      name: vpc
    subnetworkRef:
      name: vpc-subnetwork
    location: europe-west9-a
    defaultMaxPodsConstraint:
      maxPodsPerNode: 110
    resourceLabels:
      owner: crossplane
  providerConfigRef:
    name: gcp-provider-config
  writeConnectionSecretToRef:
    name: gcp-k8s
    namespace: default
