apiVersion: compute.gcp.upbound.io/v1beta1
kind: Network
metadata:
  name: vpc
  labels:
     service: vpc
     creation: crossplane
spec:
  forProvider:
    autoCreateSubnetworks: false
    description: 'This network is created by crossplane'
    routingMode: REGIONAL
  providerConfigRef:
    name: gcp-provider-config