apiVersion: compute.gcp.upbound.io/v1beta1
kind: Subnetwork
metadata:
  name: vpc-subnetwork
  labels:
     service: subnetwork
     creation: crossplane
spec:
  forProvider:
    region: europe-west9 #change if required
    ipCidrRange: "10.2.0.0/16" #change if required
    privateIpGoogleAccess: true
    networkRef:
      name: vpc
  providerConfigRef:
    name: gcp-provider-config